'use strict';
const DB_NAME='prairieHerbariumDB', STORE='records';
const defaultSettings={collector:'David R.',prefix:'DR',locality:'Hartford, South Dakota',sequence:1};
let db, currentPhotos=[];
const $=id=>document.getElementById(id);
const fields=['collectionNumber','recordStatus','collectionDate','collectionTime','locationDescription','latitude','longitude','habitat','light','soilMoisture','soilType','nearbyPlants','growthForm','height','flowerColor','abundance','phenology','specimenParts','fieldNotes','commonName','scientificName','family','confidence','identificationNotes','pressDate','dryDate','mountedDate','storageLocation','preservationNotes'];
function settings(){return {...defaultSettings,...JSON.parse(localStorage.getItem('herbariumSettings')||'{}')}}
function saveSettingsObj(s){localStorage.setItem('herbariumSettings',JSON.stringify(s))}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=e=>e.target.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=e=>{db=e.target.result;resolve(db)};r.onerror=()=>reject(r.error)})}
function tx(mode='readonly'){return db.transaction(STORE,mode).objectStore(STORE)}
function allRecords(){return new Promise((res,rej)=>{const r=tx().getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||'')));r.onerror=()=>rej(r.error)})}
function putRecord(v){return new Promise((res,rej)=>{const r=tx('readwrite').put(v);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function removeRecord(id){return new Promise((res,rej)=>{const r=tx('readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function clearRecords(){return new Promise((res,rej)=>{const r=tx('readwrite').clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function localNow(){const d=new Date();return {date:d.toISOString().slice(0,10),time:d.toTimeString().slice(0,5)}}
function nextNumber(){const s=settings(),yr=new Date().getFullYear();return `${s.prefix}-${yr}-${String(s.sequence).padStart(3,'0')}`}
function incrementSequence(){const s=settings();s.sequence=Number(s.sequence||1)+1;saveSettingsObj(s);loadSettings()}
function setView(name){document.querySelectorAll('.view,.tab').forEach(x=>x.classList.remove('active'));$(`${name}View`).classList.add('active');document.querySelector(`.tab[data-view="${name}"]`).classList.add('active');if(name==='records')renderRecords()}
function statusLabel(s){return ({field:'Field record',pressing:'Pressing',identified:'Identified',mounted:'Mounted'})[s]||s}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function card(r){const photo=r.photos?.[0]?.data;return `<article class="record-card" data-id="${r.id}">${photo?`<img class="thumb" src="${photo}" alt="">`:`<div class="thumb">No photo</div>`}<div><div class="record-title">${esc(r.collectionNumber)} — ${esc(r.commonName||r.scientificName||'Unidentified specimen')}</div><div class="record-meta">${esc(r.date||'')} · ${esc(r.habitat||'No habitat')} · ${esc(r.locationDescription||'No location')}</div></div><span class="badge">${esc(statusLabel(r.status))}</span></article>`}
async function renderDashboard(){const rows=await allRecords();$('totalCount').textContent=rows.length;$('unidentifiedCount').textContent=rows.filter(r=>!r.scientificName&&!r.commonName).length;$('mountedCount').textContent=rows.filter(r=>r.status==='mounted').length;$('speciesCount').textContent=new Set(rows.map(r=>r.scientificName?.trim().toLowerCase()).filter(Boolean)).size;$('recentRecords').innerHTML=rows.length?rows.slice(0,5).map(card).join(''):'No specimens recorded yet.';bindCards()}
async function renderRecords(){let rows=await allRecords(),q=$('searchInput').value.toLowerCase().trim(),status=$('statusFilter').value;if(q)rows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q));if(status)rows=rows.filter(r=>r.status===status);$('recordsList').innerHTML=rows.length?rows.map(card).join(''):'No matching specimens.';bindCards()}
function bindCards(){document.querySelectorAll('.record-card').forEach(c=>c.onclick=()=>editRecord(c.dataset.id))}
function resetForm(){ $('recordForm').reset(); const n=localNow(); $('recordId').value='';$('collectionNumber').value=nextNumber();$('collectionDate').value=n.date;$('collectionTime').value=n.time;$('recordStatus').value='field';currentPhotos=[];renderPhotos();$('deleteRecordBtn').classList.add('hidden');$('dialogTitle').textContent='New specimen'}
function newRecord(){resetForm();$('recordDialog').showModal()}
async function editRecord(id){const rows=await allRecords(),r=rows.find(x=>x.id===id);if(!r)return;resetForm();$('recordId').value=r.id;fields.forEach(f=>{const el=$(f);if(el)el.value=r[f.replace('recordStatus','status').replace('collectionDate','date').replace('collectionTime','time')]||''});currentPhotos=r.photos||[];renderPhotos();$('deleteRecordBtn').classList.remove('hidden');$('dialogTitle').textContent=r.collectionNumber;$('recordDialog').showModal()}
function renderPhotos(){$('photoPreview').innerHTML=currentPhotos.map((p,i)=>`<div class="photo-item"><img src="${p.data}" alt="Specimen photo"><button type="button" data-photo="${i}" aria-label="Remove photo">×</button></div>`).join('');document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>{currentPhotos.splice(Number(b.dataset.photo),1);renderPhotos()})}
function resizeImage(file,max=1400,quality=.78){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{let w=img.width,h=img.height;if(Math.max(w,h)>max){const s=max/Math.max(w,h);w*=s;h*=s}const c=document.createElement('canvas');c.width=Math.round(w);c.height=Math.round(h);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve({name:file.name,data:c.toDataURL('image/jpeg',quality)})};img.onerror=reject;img.src=reader.result};reader.onerror=reject;reader.readAsDataURL(file)})}
async function saveForm(e){e.preventDefault();const isNew=!$('recordId').value,id=$('recordId').value||crypto.randomUUID(),obj={id,createdAt:new Date().toISOString()};fields.forEach(f=>{const key=f.replace('recordStatus','status').replace('collectionDate','date').replace('collectionTime','time');obj[key]=$(f).value.trim?.()??$(f).value});if(!isNew){const old=(await allRecords()).find(x=>x.id===id);obj.createdAt=old.createdAt}obj.updatedAt=new Date().toISOString();obj.photos=currentPhotos;obj.collector=settings().collector;await putRecord(obj);if(isNew)incrementSequence();$('recordDialog').close();toast('Specimen saved');renderDashboard();renderRecords()}
function csvCell(v){return `"${String(v??'').replaceAll('"','""')}"`}
async function exportCSV(){const rows=await allRecords(),keys=['collectionNumber','date','time','status','commonName','scientificName','family','confidence','locationDescription','latitude','longitude','habitat','light','soilMoisture','soilType','growthForm','height','flowerColor','abundance','phenology','specimenParts','fieldNotes','pressDate','dryDate','mountedDate','storageLocation','preservationNotes'];download('herbarium-records.csv',[keys.join(','),...rows.map(r=>keys.map(k=>csvCell(r[k])).join(','))].join('\n'),'text/csv')}
async function exportJSON(){download(`herbarium-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({version:1,exportedAt:new Date().toISOString(),settings:settings(),records:await allRecords()},null,2),'application/json')}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importJSON(file){try{const data=JSON.parse(await file.text());if(!Array.isArray(data.records))throw Error('Invalid backup');for(const r of data.records)await putRecord(r);if(data.settings)saveSettingsObj(data.settings);loadSettings();renderDashboard();renderRecords();toast(`${data.records.length} records restored`)}catch(e){alert('This does not appear to be a valid Prairie Herbarium backup.')}}
function printHTML(html,title){const w=window.open('','_blank');w.document.write(`<!doctype html><html><head><title>${title}</title><link rel="stylesheet" href="style.css"></head><body>${html}<script>onload=()=>print()<\/script></body></html>`);w.document.close()}
function printFieldCards(){const s=settings(),one=`<section class="field-card"><h2>Plant Collection Field Record</h2><b>Collection #:</b><div class="line"></div><b>Date / Time:</b><div class="line"></div><b>Location / GPS:</b><div class="line"></div><div class="line"></div><b>Habitat:</b><div class="checkrow">□ Prairie □ Roadside □ Pasture<br>□ Woodland □ Wetland □ Water edge<br>□ Lawn □ Disturbed □ Other</div><b>Conditions:</b><div class="checkrow">□ Sun □ Part shade □ Shade<br>□ Dry □ Moist □ Wet</div><b>Plant:</b><div class="checkrow">□ Forb □ Grass □ Sedge □ Shrub<br>□ Tree □ Vine □ Fern □ Other</div><b>Height / flower color:</b><div class="line"></div><b>Photos:</b><div class="checkrow">□ Habitat □ Whole □ Flower<br>□ Leaves □ Stem □ Fruit/seed</div><b>Parts collected:</b><div class="line"></div><b>Notes:</b><div class="line"></div><div class="line"></div><div class="line"></div><small>${esc(s.collector)} · ${esc(s.locality)}</small></section>`;printHTML(`<main class="field-card-page">${one}${one}${one}</main>`,'Field Cards')}
async function printLabel(){const id=$('recordId').value;let r={};fields.forEach(f=>{const key=f.replace('recordStatus','status').replace('collectionDate','date').replace('collectionTime','time');r[key]=$(f).value});r.collector=settings().collector;const html=`<main style="padding:.4in"><section class="label-print"><div><b>${esc(r.family||'Plant specimen')}</b></div><h2>${esc(r.scientificName||'Identification pending')}</h2><div>${esc(r.commonName||'')}</div><p><b>Collection:</b> ${esc(r.collectionNumber)}<br><b>Date:</b> ${esc(r.date)}<br><b>Collector:</b> ${esc(r.collector)}</p><p><b>Locality:</b> ${esc(r.locationDescription||settings().locality)}${r.latitude?`<br><b>Coordinates:</b> ${esc(r.latitude)}, ${esc(r.longitude)}`:''}</p><p><b>Habitat:</b> ${esc([r.habitat,r.light,r.soilMoisture,r.soilType].filter(Boolean).join('; '))}</p><p>${esc(r.fieldNotes||r.identificationNotes||'')}</p></section></main>`;printHTML(html,`${r.collectionNumber} label`)}
function loadSettings(){const s=settings();$('collectorSetting').value=s.collector;$('prefixSetting').value=s.prefix;$('localitySetting').value=s.locality;$('sequenceSetting').value=s.sequence}
async function init(){await openDB();loadSettings();renderDashboard();renderRecords();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>setView(b.dataset.go));$('newRecordBtn').onclick=newRecord;$('closeDialogBtn').onclick=()=>$('recordDialog').close();$('recordForm').addEventListener('submit',saveForm);$('searchInput').oninput=renderRecords;$('statusFilter').onchange=renderRecords;$('exportCsvBtn').onclick=exportCSV;$('exportJsonBtn').onclick=exportJSON;$('importJsonInput').onchange=e=>e.target.files[0]&&importJSON(e.target.files[0]);$('printFieldCardsBtn').onclick=printFieldCards;$('printLabelBtn').onclick=printLabel;$('photoInput').onchange=async e=>{for(const f of e.target.files)currentPhotos.push(await resizeImage(f));renderPhotos();e.target.value=''};$('gpsBtn').onclick=()=>{if(!navigator.geolocation)return toast('GPS not available');$('gpsStatus').textContent='Locating…';navigator.geolocation.getCurrentPosition(p=>{$('latitude').value=p.coords.latitude.toFixed(6);$('longitude').value=p.coords.longitude.toFixed(6);$('gpsStatus').textContent=`Accuracy ±${Math.round(p.coords.accuracy)} m`},e=>$('gpsStatus').textContent=`Unable to locate: ${e.message}`,{enableHighAccuracy:true,timeout:15000})};$('deleteRecordBtn').onclick=async()=>{if(confirm('Delete this specimen record permanently?')){await removeRecord($('recordId').value);$('recordDialog').close();renderDashboard();renderRecords();toast('Record deleted')}};$('saveSettingsBtn').onclick=()=>{saveSettingsObj({collector:$('collectorSetting').value.trim(),prefix:$('prefixSetting').value.trim().toUpperCase()||'DR',locality:$('localitySetting').value.trim(),sequence:Number($('sequenceSetting').value)||1});toast('Settings saved')};$('clearAllBtn').onclick=async()=>{if(confirm('Delete every locally stored record and photo? This cannot be undone.')){await clearRecords();renderDashboard();renderRecords();toast('All records deleted')}};init();
